# Generated by Django 3.1.5 on 2021-01-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100, verbose_name='用途')),
                ('name', models.CharField(choices=[('Taro', 'Taro'), ('Koki', 'Koki'), ('Kaze', 'Kaze')], max_length=100, verbose_name='名前')),
                ('amount', models.IntegerField(verbose_name='金額(円)')),
                ('posted_date', models.DateTimeField(auto_now_add=True, verbose_name='時刻')),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
    ]
